### ISSUE TITLE
Exception when using Python SDK for Kratos registration

### ISSUE THREAD

**Issue by AntiSC2** [ory/sdk#10]
Kratos version: v0.1.1-alpha.1
Oathkeeper version: v0.37.1-beta.1
SDK version: 0.1.1a1 

When calling: 
`api_response = api_instance.get_self_service_browser_registration_request(request)`
I get the following exception:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1701, in _execute
result = method(*self.path_args, **self.path_kwargs)
File "/app/app/web/handlers/authentication.py", line 62, in get
api_response = api_instance.get_self_service_browser_registration_request(request)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api/public_api.py", line 514, in get_self_service_browser_registration_request
return self.get_self_service_browser_registration_request_with_http_info(request, **kwargs)  # noqa: E501
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api/public_api.py", line 583, in get_self_service_browser_registration_request_with_http_info
return self.api_client.call_api(
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 348, in call_api
return self.__call_api(resource_path, method,
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 192, in __call_api
return_data = self.deserialize(response_data, response_type)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 264, in deserialize
return self.__deserialize(data, response_type)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 303, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 639, in __deserialize_model
kwargs[attr] = self.__deserialize(value, attr_type)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 285, in __deserialize
return {k: self.__deserialize(v, sub_kls)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 285, in <dictcomp>
return {k: self.__deserialize(v, sub_kls)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 303, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 639, in __deserialize_model
kwargs[attr] = self.__deserialize(value, attr_type)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 303, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 639, in __deserialize_model
kwargs[attr] = self.__deserialize(value, attr_type)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 280, in __deserialize
return [self.__deserialize(sub_data, sub_kls)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 280, in <listcomp>
return [self.__deserialize(sub_data, sub_kls)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 303, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/api_client.py", line 641, in __deserialize_model
instance = klass(**kwargs)
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/models/form_field.py", line 77, in __init__
self.required = required
File "/usr/local/lib/python3.8/site-packages/ory_kratos_client/models/form_field.py", line 197, in required
raise ValueError("Invalid value for `required`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `required`, must not be `None`
```

My identity.traits.schema.json for Kratos:
```
{
  "$id": "https://example.org/registration.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Member",
  "type": "object",
  "properties": {
    "email": {
      "type": "string",
      "format": "email",
      "title": "E-Mail",
      "minLength": 3,
      "ory.sh/kratos": {
        "credentials": {
          "password": {
            "identifier": true
          }
        },
        "verification": {
          "via": "email"
        }
      }
    }
  },
  "required": [
    "email"
  ],
  "additionalProperties": false
}
```

I don't have any problems with the login flow, only when calling the registration flow.

**Comment by aeneasr** [comment]
Looks like you maybe forgot to set a field? Or is that an error from the response?

**Comment by AntiSC2** [comment]
This is an error coming from the response

**Comment by AntiSC2** [comment]
Here is the JSON response from Kratos, it seems that the email field does not have the required field and this seems to be causing a problem when the SDK tries to create the Python object for the form field.

```
{
  "id": "3316e963-c779-492b-b932-1670bf81fdb1",
  "expires_at": "2020-04-06T18:54:09.717088382Z",
  "issued_at": "2020-04-06T18:44:09.717088772Z",
  "request_url": "http://127.0.0.1:4455/self-service/browser/flows/registration",
  "methods": {
    "oidc": {
      "method": "oidc",
      "config": {
        "action": "http://127.0.0.1:4455/.ory/kratos/public/self-service/browser/flows/registration/strategies/oidc/auth/3316e963-c779-492b-b932-1670bf81fdb1",
        "method": "POST",
        "fields": [
          {
            "name": "csrf_token",
            "type": "hidden",
            "required": true,
            "value": "tBlX55mgM73IPLLWZT+NgnN8IZz9DvjFI1IqsJ9gjbE4L33JsIhdPjONqvdY0kXixG4EpB6iB1GNGVdmvtPuoA=="
          }
        ]
      }
    },
    "password": {
      "method": "password",
      "config": {
        "action": "http://127.0.0.1:4455/.ory/kratos/public/self-service/browser/flows/registration/strategies/password?request=3316e963-c779-492b-b932-1670bf81fdb1",
        "method": "POST",
        "fields": [
          {
            "name": "csrf_token",
            "type": "hidden",
            "required": true,
            "value": "tBlX55mgM73IPLLWZT+NgnN8IZz9DvjFI1IqsJ9gjbE4L33JsIhdPjONqvdY0kXixG4EpB6iB1GNGVdmvtPuoA=="
          },
          {
            "name": "password",
            "type": "password",
            "required": true
          },
          {
            "name": "traits.email",
            "type": "email"
          }
        ]
      }
    }
  }
}
```

**Comment by aeneasr** [comment]
Thank you, that is indeed the case! I've pushed a fix to ORY Kratos which will resolve this with the next release.
