### ISSUE TITLE
[Kratos] TypeScript Client SDK throws error in browser

### ISSUE THREAD

**Issue by mrcageman** [ory/sdk#13]
When trying to import e.g. the `PublicApi` in a React project, it tries to include multiple server-side modules such as `fs`, `request` etc.

This causes the following error to be thrown:

```
Module not found: Can't resolve 'fs' in '/Users/.../app/node_modules/request/lib'
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/Users/.../app/node_modules/request/lib'
    at factory.create (/Users/.../app/node_modules/webpack/lib/Compilation.js:925:10)
    at factory (/Users/.../app/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/Users/.../app/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/.../app/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/.../app/node_modules/neo-async/async.js:2830:7
    at /Users/.../app/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/Users/.../app/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/.../app/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
    at hook.callAsync (/Users/.../app/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/.../app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/.../app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/Users/.../app/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/.../app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/.../app/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/.../app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/.../app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
```

**Comment by aeneasr** [comment]
For which project does that happen?

**Comment by mrcageman** [comment]
It happens with the Kratos client.

**Comment by aeneasr** [comment]
Ok, I haven't used the SDK for client side apps yet but we're going to do that soon so hopefully we'll be able to replicate it and fix it!

**Comment by aeneasr** [comment]
I can't reproduce this, it's probably an issue with your webpack module.

Here's what I did:

```
$ npx create-react-app foo
$ cd foo
$ npm add @oryd/kratos-client
$ open src/index.js
```

Modify file:

```
//...
import {AdminApi} from '@oryd/kratos-client'
const adminEndpoint = new AdminApi("")
//...
```

start server:

```
$ npm run start
```

Everything works as expected.
