### ISSUE TITLE
Ory Hydra Client for Elixir has a typo which breaks the client

### ISSUE THREAD

**Issue by ah0y** [ory/sdk#285]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

 ```elixir
  def authorization(token, _scopes) when is_binary(token) do
    {Tesla.Middleware.Headers, ["authorization", token]}
  end
  ```
  
  should be
  
  ```elixir
 def authorization(token, _scopes) when is_binary(token) do
     {Tesla.Middleware.Headers, [{"authorization", token}]}
  end
  ```
  
  

### Reproducing the bug

Try running any requests

### Relevant log output

```shell
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Tesla.Adapter.Httpc.request/2    
    
    The following arguments were given to anonymous fn/1 in Tesla.Adapter.Httpc.request/2:
    
        # 1
        "authorization"
    
    (tesla 1.7.0) lib/tesla/adapter/httpc.ex:55: anonymous fn/1 in Tesla.Adapter.Httpc.request/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (tesla 1.7.0) lib/tesla/adapter/httpc.ex:55: Tesla.Adapter.Httpc.request/2
    (tesla 1.7.0) lib/tesla/adapter/httpc.ex:22: Tesla.Adapter.Httpc.call/2
    (ory_hydra 2.2.0-pre.0) lib/ory/api/o_auth2.ex:644: Ory.Api.OAuth2.o_auth2_authorize/2
    iex:5: (file)
```
```


### Relevant configuration

_No response_

### Version

e471477af9c733ee7b84a6c869a35d4a5f17b67e

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Ory Network

### Additional Context

_No response_

**Comment by tobbbles** [comment]
I've proposed a fix to the upstream generator.

This will need to be fixed upstream and we'll look to upgrade the elixir generation to 7.0.1 of the openapi-generator once it's released.

However there is currently a breaking change in 7.0.0 preventing us to upgrade, so we will need to wait until https://github.com/OpenAPITools/openapi-generator/issues/16412 is resolved before moving forward
