### ISSUE TITLE
Elixir API client deserialisation error when parsing enum values

### ISSUE THREAD

**Issue by tomwilsn** [ory/sdk#355]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The elixir client has some issues when parsing response data that contains "enums"

### Reproducing the bug

E.g. when calling: `Ory.Api.Frontend.to_session(Ory.Connection.new, [Cookie: cookie])`

I get the following error: 

```** (FunctionClauseError) no function clause matching in Ory.Deserializer.to_struct/2

    The following arguments were given to Ory.Deserializer.to_struct/2:

        # 1
        "aal1"

        # 2
        Ory.Model.AuthenticatorAssuranceLevel

    Attempted function clauses (showing 3 out of 3):

        defp to_struct(nil, _)
        defp to_struct(list, module) when is_list(list) and is_atom(module)
        defp to_struct(map, module) when is_map(map) and is_atom(module)

    (ory_client 1.6.2) lib/ory/deserializer.ex:97: Ory.Deserializer.to_struct/2
    (elixir 1.15.7) lib/map.ex:916: Map.update!/3
    (ory_client 1.6.2) lib/ory/model/session_authentication_method.ex:31: Ory.Model.SessionAuthenticationMethod.decode/1
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.15.7) lib/map.ex:916: Map.update!/3
    (ory_client 1.6.2) lib/ory/model/session.ex:42: Ory.Model.Session.decode/1
    (ory_client 1.6.2) lib/ory/deserializer.ex:19: Ory.Deserializer.jason_decode/2
    iex:2: (file)
```

It is potentially caused by this bug I found on the open-api-generator GitHub: https://github.com/OpenAPITools/openapi-generator/issues/16412

### Version

1.6

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by binajmen** [comment]
@aeneasr Apologies for the ping, but is this bug being tracked? I want to integrate Ory into our Elixir API server, but the Ory client isn't usable in its current state.

**Comment by tobbbles** [comment]
This ought to be solved as of [v0.0.59](https://github.com/ory/sdk/releases/tag/v0.0.59) of the sdk thanks to upstream changes in openapi-generator 7.12.0
