### ISSUE TITLE
0.6.0+ JsonSyntaxException

### ISSUE THREAD

**Issue by notmeta** [ory/sdk#74]
First of all, thanks for Ory Kratos.
Currently experimenting with it, and so far it's great, can't wait for more features (like MFA!).

I've been trying out the latest generated clients from Maven, however when running `apiInstance.initializeSelfServiceLoginViaAPIFlow` I get a JsonSyntaxException.
I haven't tried all endpoints, other than version and health check from the admin api (which work fine).

I've just been using the example given [here](https://github.com/ory/kratos-client-java/blob/master/docs/PublicApi.md#initializeSelfServiceLoginViaAPIFlow).

I've tried with `0.5.4-alpha.1` and it works as expected, however on `0.6.1-alpha.1`/`0.6.0-alpha.17`/`0.6.0-alpha.13` it does not (haven't tested more versions).

Error:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 443 path $.ui.nodes[0].attributes.value
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at sh.ory.kratos.JSON.deserialize(JSON.java:146)
	at sh.ory.kratos.ApiClient.deserialize(ApiClient.java:797)
	at sh.ory.kratos.ApiClient.handleResponse(ApiClient.java:1003)
	at sh.ory.kratos.ApiClient.execute(ApiClient.java:927)
	at sh.ory.kratos.api.PublicApi.initializeSelfServiceLoginViaAPIFlowWithHttpInfo(PublicApi.java:1161)
	at sh.ory.kratos.api.PublicApi.initializeSelfServiceLoginViaAPIFlow(PublicApi.java:1140)
...
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 443 path $.ui.nodes[0].attributes.value
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 40 more
```

Not super duper concerned, it's still alpha after all and I'm still going to experiment with Kratos, but would definitely be nice to have this fixed :smile: 
Worst case scenario I'll implement my own api client.

Thanks!

**Comment by aeneasr** [comment]
Hey there, I moved this to ory/sdk as this is the place where code is generated. We had similar reports for rust ( https://github.com/ory/sdk/issues/72 )  and CSharp and it appears that this is the same issue. May I ask of you to create an issue report with openapi-generator similar to this one ( https://github.com/OpenAPITools/openapi-generator/issues/9442 )? I have no Java experience so unfortunately I can't fix this in the generator

**Comment by aeneasr** [comment]
I might have found a solution - check out: https://github.com/ory/sdk/issues/75#issuecomment-844461783

Could you check if that solves the issue?
