### ISSUE TITLE
[Kratos Ruby SDK] How to setup the sdk in ruby.

### ISSUE THREAD

**Issue by lucassimon** [ory/sdk#77]
Hello, 

I have some problems when start to use the sdk on a ruby gem.

``` 
Traceback (most recent call last):
	7: from bin/console:4:in `<main>'
	6: from bin/console:4:in `require'
	5: from /home/lucas/workspaces/ferreri/prever/ferreri_kratos_sdk/lib/ferreri_kratos_sdk.rb:3:in `<top (required)>'
	4: from /home/lucas/workspaces/ferreri/prever/ferreri_kratos_sdk/lib/ferreri_kratos_sdk.rb:3:in `require'
	3: from /home/lucas/workspaces/ferreri/prever/ferreri_kratos_sdk/lib/ferreri_kratos_sdk/clients/ory.rb:1:in `<top (required)>'
	2: from /home/lucas/workspaces/ferreri/prever/ferreri_kratos_sdk/lib/ferreri_kratos_sdk/clients/ory.rb:1:in `require'
	1: from /home/lucas/.rvm/gems/ruby-2.7.3/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client.rb:17:in `<top (required)>'
/home/lucas/.rvm/gems/ruby-2.7.3/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client.rb:17:in `require': /home/lucas/.rvm/gems/ruby-2.7.3/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:228: syntax error, unexpected ',' (SyntaxError)
            in: ,
                ^
/home/lucas/.rvm/gems/ruby-2.7.3/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:229: syntax error, unexpected ',', expecting `end'
...     key: 'ory_kratos_session',
...                              ^
/home/lucas/.rvm/gems/ruby-2.7.3/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:231: syntax error, unexpected '}', expecting `end'
          },
          ^
/home/lucas/.rvm/gems/ruby-2.7.3/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:232: syntax error, unexpected =>, expecting `end'
        'sessionToken' =>
                       ^~
/home/lucas/.rvm/gems/ruby-2.7.3/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:238: syntax error, unexpected ',', expecting `end'
          },
           ^
/home/lucas/.rvm/gems/ruby-2.7.3/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:291: syntax error, unexpected end-of-input, expecting `end'

``` 

I am trying:

```
# the error occurred here
require 'ory-kratos-client'

configuration = OryHydraClient::Configuration.New(
    host = "http://localhost:4433"
)

module FerreriKratosSdk
    module Clients        
        class ClientOry
            def initialize
                # configuration = OryHydraClient::Configuration.New(
                #     host = "http://localhost:4433"
                # )
                # @cli = OryHydraClient::PublicApi.new(config=configuration)

            end 
```

**Comment by lucassimon** [comment]
``` 
web_1           | Fast Debugger (ruby-debug-ide 0.7.2, debase 0.2.4.1, file filtering is supported) listens on 0.0.0.0:1234
db-migration_1  | rails aborted!
db-migration_1  | SyntaxError: /usr/local/bundle/gems/ory-client-0.0.1.alpha9/lib/ory-client/configuration.rb:228: syntax error, unexpected ','
db-migration_1  |             in: ,
db-migration_1  |                 ^
db-migration_1  | /usr/local/bundle/gems/ory-client-0.0.1.alpha9/lib/ory-client/configuration.rb:229: syntax error, unexpected ',', expecting `end'
db-migration_1  | ...     key: 'ory_kratos_session',
db-migration_1  | ...                              ^
db-migration_1  | /usr/local/bundle/gems/ory-client-0.0.1.alpha9/lib/ory-client/configuration.rb:231: syntax error, unexpected '}', expecting `end'
db-migration_1  |           },
db-migration_1  |           ^
db-migration_1  | /usr/local/bundle/gems/ory-client-0.0.1.alpha9/lib/ory-client/configuration.rb:232: syntax error, unexpected =>, expecting `end'
db-migration_1  |         'sessionToken' =>
db-migration_1  |                        ^~
db-migration_1  | /usr/local/bundle/gems/ory-client-0.0.1.alpha9/lib/ory-client/configuration.rb:238: syntax error, unexpected ',', expecting `end'
db-migration_1  |           },
db-migration_1  |            ^
db-migration_1  | /usr/local/bundle/gems/ory-client-0.0.1.alpha9/lib/ory-client/configuration.rb:297: syntax error, unexpected end-of-input, expecting `end'
db-migration_1  | /api/enginies/profiles/lib/profiles/session.rb:1:in `<main>'
db-migration_1  | /api/config/initializers/profiles.rb:1:in `<main>'
db-migration_1  | /api/config/environment.rb:7:in `<main>'
db-migration_1  | /api/bin/rails:9:in `<top (required)>'
db-migration_1  | /api/bin/spring:15:in `require'
db-migration_1  | /api/bin/spring:15:in `<top (required)>'
db-migration_1  | Tasks: TOP => db:prepare => db:load_config => environment
db-migration_1  | (See full trace by running task with --trace)
user-service_db-migration_1 exited with code 1
```

**Comment by aeneasr** [comment]
Dupe kraots#1426

**Comment by aeneasr** [comment]
https://github.com/ory/kratos/issues/1426
